### PR TITLE
fix(GuildChannel|Role.edit) Editing with a position not being right

### LINKED ISSUE #1974: channel.edit({position: value}) is editing rawPosition and not position (aka can't move channels inside of categories)
**Please describe the problem you are having in as much detail as possible:**

Test Case 1: When you do `currentChannel.edit({ position: currentPosition })` it's not editing `position` it's instead editing `rawPosition`

Test Case 2: When you do `currentChannel.edit({ rawPosition: currentPosition })` it properly edits `rawPosition`

**Include a reproducible code sample here, if possible:**

The below code is used to store channel order in memory and incrementally reorder them for easy channel cloning and reordering later.

```js
    orderChannels: function () {
        var channelsOrdered = client.channels.array().slice(0);
        channelsOrdered = channelsOrdered.filter(function (channel) {
            return channel.type == 'voice' && typeof channel.position !== 'undefined';
        });


        channelsOrdered = channelsOrdered.sort(function (channelA, channelB) {
            return channelA.rawPosition - channelB.rawPosition;
        })
        
        var currentPosition = 2;
        channelsOrdered.forEach(function (channel) {
            currentChannel = client.channels.get(channel.id);
            currentChannel.edit({ bitrate: 96000, position: currentPosition })
                .then(channel => {
                    console.log(channel.type + ' channel: ' +channel.name + ' position set to: ' + channel.position + ' & rawPosition set to: ' + channel.rawPosition)
                })
                .catch(console.error);
            currentPosition = currentPosition + 2;
        });

        console.log(channelsOrdered)
    }
```

**Further details:**

- discord.js version: 12.0.0-dev
- node.js version: v8.4.0
- Operating system: Windows
- Priority this issue should have – please be realistic and elaborate if possible: **Medium-High** (as this is a bug that effects editing channels directly)

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by KingDGrizzle**
**Please describe the changes this PR makes and why it should be merged:**
This PR fixes the `edit({ position: 1 })` issues, where editing a position would do nothing.
Now, if position wants to be changed, it'll attempt to change it, and if it was able to move the channel, it'll continue with the rest of the edit.

Tested and it works as expected. Works with other options as well.
This is probably janky, but it works as intended now. ~I might have to change some docs for the meaning of the position param~

This should also fix #1974 

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/util/Util.js [hunk 1]
```diff
@@ -316,6 +316,30 @@ class Util {
     }
     return f;
   }
+
+  static editPosition(item, position, sorted, route, type, reason) {
```
Comment (SpaceEEC) [inline src/util/Util.js]: Instead of creating a new method here, you can probably use `setPosition`.
Something like this could work:
```js
Util.setPosition(...).then(updatedItems =>
    this.client.actions.GuildChannelsPositionUpdate.handle({
        guild_id: this.guild.id,
        channels: updatedItems,
    });
```

File: src/structures/GuildChannel.js [hunk 2]
```diff
@@ -276,11 +276,14 @@ class GuildChannel extends Channel {
    *   .catch(console.error);
    */
   edit(data, reason) {
+    if (typeof data.position !== 'undefined') {
+      Util.editPosition(this, data.position, this.guild._sortedChannels(this),
+        this.client.api.guilds(this.guild.id).channels, 'channel', reason).catch(err => Promise.reject(err));
```
[the remark this answers is not in the document]
Comment (KingDGrizzle) [reply src/structures/GuildChannel.js]: Well, the catch returns the missing permission error from the route.patch, and "throws" it. Can't think of a better solution right now tho

File: src/util/Util.js (hunk 1 above)
Comment (KingDGrizzle) [reply src/util/Util.js]: I was thinking about that too, but I did it this way so that it happens all in one function, without having to .then it and do it in the main edit function.

I will experiment with it tho.
