### PR TITLE
fix(TextBasedChannel): return a promise in startTyping and clarify count parameter

### LINKED ISSUE #2040: channel.startTyping() promise rejections
**Please describe the problem you are having in as much detail as possible:**
`channel.startTyping()` continuously throws promise rejection warnings if the bot doesn't have permission to send messages. Is it possible for discord.js to stop trying to type if the bot doesn't have permission? If this is expected behavior, is there a way I can call `channel.stopTyping()` after permission is taken away while the bot has already started typing?

**Include a reproducible code sample here, if possible:**
1. Type "start" to have the bot start typing.
2. Disable the bot's permission to send messages in the channel.
3. Node begins emitting UnhandledPromiseRejectionWarning every few seconds.

```js
let Discord = require('discord.js');
let bot = new Discord.Client();

bot.on('ready', function() {
	console.log(Discord.version);
});

bot.on('message', function(message) {
	if (message.content == 'start')
		message.channel.startTyping();
	if (message.content == 'stop')
		message.channel.stopTyping();
});

bot.login('...');
```

```
12.0.0-dev
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DiscordAPIError: Missing Access
(node:6636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): DiscordAPIError: Missing Access
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): DiscordAPIError: Missing Access
```
**Further details:**

- discord.js version: 12.0.0-dev (discovered in stable)
- node.js version: 8.7.0
- Operating system: Windows 8 and Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: low

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: 68a30584db44580d1e00e6da57e24e0ae5bb1808

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**
This fixes #2040

Calling TextBasedChannel#startTyping now returns a promise.
This promise resolves when the bot stops typing (TextBasedChannel#stopTyping) or rejects when an error occurs.
Calling the method again returns the same promise as long the bot is still typing.

This is probably not the most elegant solution.
I am open for any suggestions.

Edit:
I also clarified what the count parameter is actually doing and how it is working.

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

File: src/structures/interfaces/TextBasedChannel.js [hunk 1]
```diff
@@ -159,25 +159,42 @@ class TextBasedChannel {
...
    * @example
    * // Start typing in a channel
    * channel.startTyping();
    */
   startTyping(count) {
     if (typeof count !== 'undefined' && count < 1) throw new RangeError('TYPING_COUNT');
     if (!this.client.user._typing.has(this.id)) {
+      let resolve;
+      let reject;
+      const promise = new Promise((res, rej) => { [resolve, reject] = [res, rej]; });
```
Comment (devsnek) [inline src/structures/interfaces/TextBasedChannel.js]: this is a huge evil anti-pattern, just wrap the following code in a promise and set it in the entry or return it

File: src/structures/interfaces/TextBasedChannel.js [hunk 2]
```diff
@@ -159,25 +159,41 @@ class TextBasedChannel {
...
     if (typeof count !== 'undefined' && count < 1) throw new RangeError('TYPING_COUNT');
     if (!this.client.user._typing.has(this.id)) {
-      const endpoint = this.client.api.channels[this.id].typing;
-      this.client.user._typing.set(this.id, {
-        count: count || 1,
-        interval: this.client.setInterval(() => {
-          endpoint.post();
-        }, 9000),
+      const entry = {};
+      entry.promise = new Promise((resolve, reject) => {
```
Comment (devsnek) [inline src/structures/interfaces/TextBasedChannel.js]: you can do
```js
const entry = {
  promise: ...
}
```

Comment (SpaceEEC) [reply src/structures/interfaces/TextBasedChannel.js]: That would cause the `entry` variable to be undefined in the promise' executor.

Comment (devsnek) [reply src/structures/interfaces/TextBasedChannel.js]: sounds good
