### PR TITLE
ClientUser Fixes

### LINKED ISSUE #1702: setUsername not working on user account bots
Hello everyone,
I trying to change a userbot's username using the setUsername function. However, whenever I try to call it, it says "password: Password does not match.". I know the password is correct. Does anyone know how I can solve this issue?
Here's my code.
`client.login('my token')
client.password = 'my password'
client.on('ready', () => {
client.user.setUsername('mybot','my password')
});`

Thank you,
Josh

### PR DESCRIPTION
**Pull request by CyberiumShadow**
**Please describe the changes this PR makes and why it should be merged:**
This fixes #1702 by correctly applying the password to the data object sent to the Discord API
This also fixes `<ClientUser>.setPassword` for MFA-enabled accounts by allowing the user to pass an MFA Code to the method
This also updates the token stored in `client.token` when any security related method is used on the clientUser

**Semantic versioning classification:**  
- [x] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
This should be complete. Can contribs please check this over?

**Comment by appellation** [comment]
Well, your build failed.  So you should probably fix that first.

**Comment by KingDGrizzle** [comment]
`  147:3  error  Missing JSDoc for parameter 'options'  valid-jsdoc`

I think you forgot to document the options object for edit

**Comment by CyberiumShadow** [comment]
Travis Build error fixed lol...

File: src/structures/ClientUser.js [hunk 1]
```diff
@@ -147,16 +148,18 @@ class ClientUser extends User {
    * Changes the password for the client user's account.
    * <warn>This is only available when using a user account.</warn>
    * @param {string} newPassword New password to change to
-   * @param {string} oldPassword Current password
+   * @param {?Object} options Options object containing either an MFA code, password or both.
```
Comment (PgBiel) [inline src/structures/ClientUser.js]: {Object}

**Comment by KingDGrizzle** [comment]
Line 151 exceeds the max length.
I don't get why you placed `Object|string` in parentheses, and also, the object documentation might be better as (and this is the full JS line):
` * @param {Object|string} options Object containing an MFA Code, a password or both. Can be just a string for the password`

_Keep in mind its just a suggestion / question_

**Comment by CyberiumShadow** [comment]
@KingDGrizzle @iCrawl any JSDocs that I did, were referenced from the JSDocs site, and it had multiple types in parens. I'll be fixing it asap

**Comment by CyberiumShadow** [comment]
all gucci me thinks
