### PR TITLE
Fixed ClientUser#createGroupDM on user accounts and added some more GroupDMChannel stuff

### LINKED ISSUE #1746: createGroupDM Parameters do not resolve correctly according to Documentation
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**
```js
/**
 * @type {SnowFlake} WITH
 * @type {Discord.Client} HAMMER
 * @type {Discord.Client} CLOUD
 */
CLOUD.user.createGroupDM([{id: HAMMER.user.id}, {id: WITH}])
```

**Further details:**

- discord.js version: master, `discord.js@12.0.0-dev`
- node.js version: 7.7.2
- Operating system: Windows 10, Pro
- Priority this issue should have – please be realistic and elaborate if possible:
> This should only be solved if Discord.js is diving into Group DM's, which i dont see happening that fast.
> Regardless, i want to make a intra-skype-discord bot for a few friends that refuse to use the other platform.
> This is not a breaking issue, as it is trying to solve `UserResolvable`, instead of `GroupDMRecipientOptions`, which i can easily adjust to, but the code is not acting as expected from the [documents](https://discord.js.org/#/docs/main/master/typedef/GroupDMRecipientOptions) (as elaborated below)

- [x ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

### PR DESCRIPTION
**Pull request by SpaceEEC**
**Please describe the changes this PR makes and why it should be merged:**

Fixes #1746
The method was expecting an array of `UserResolvable`s which is differently than the docs stated.
Going with an array of `GroupDMRecipientOptions` as it seems more natural.
Also removed an incorrect warning as the user property will be used on bot accounts.

Edit:
- Added `GroupDMChannel#setIcon`
- Fixed null handling for Group DM channel names, as they are nullable.

More commits:
- Added `GroupDMChannel#iconURL`

**Semantic versioning classification:**  
- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
Thanks :)

**Comment by ShadowJonathan** [comment]
Potentional bug: When calling `setIcon` here, it'll also call a `null` to `name` on the body, resetting the group name, and possibly vice versa with `icon`

File: src/structures/GroupDMChannel.js [hunk 1]
```diff
@@ -131,15 +131,31 @@ class GroupDMChannel extends Channel {
    * @returns {Promise<GroupDMChannel>}
    */
   edit(data, reason) {
+    const name = data.name === null ? null : data.name || this.name;
```
Comment (devsnek) [inline src/structures/GroupDMChannel.js]: should be `data.name !== null ? data.name : this.name`

File: src/structures/GroupDMChannel.js [hunk 2]
```diff
@@ -131,15 +131,31 @@ class GroupDMChannel extends Channel {
...
     return this.client.api.channels[this.id].patch({
       data: {
-        name: (data.name || this.name).trim(),
+        icon: data.icon,
+        name: name === null ? null : name.trim(),
```
Comment (devsnek) [inline src/structures/GroupDMChannel.js]: just put `name`

File: src/structures/GroupDMChannel.js [hunk 3]
```diff
@@ -131,15 +131,31 @@ class GroupDMChannel extends Channel {
...
   /**
+   * Sets a new icon for this Group DM.
+   * @param {Base64Resolvable} icon The new icon of this Group DM
+   * @returns {Promise<GroupDMChannel>}
+   */
+  setIcon(icon) {
+    if (typeof icon === 'string' && icon.startsWith('data:')) {
+      return this.edit({ icon });
+    } else {
+      return this.client.resolver.resolveBuffer(icon || Buffer.alloc(0))
```
Comment (devsnek) [inline src/structures/GroupDMChannel.js]: if icon is empty or something ffs don't bother with resolving a buffer

**Comment by ShadowJonathan** [comment]
Cevermind, it passes the current name if none is passed, but its still weird to look at

File: src/structures/GroupDMChannel.js (hunk 3 above)
Comment (SpaceEEC) [inline src/structures/GroupDMChannel.js]: almost committed

File: src/structures/GroupDMChannel.js (hunk 1 above)
Comment (SpaceEEC) [inline src/structures/GroupDMChannel.js]: I don't need to trim then?
